In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [3]:
print(a[0])

[1 2 3 4]


In [4]:
a1 = np.array([1, 2, 3])

In [5]:
np.zeros(2)

array([0., 0.])

In [6]:
np.ones(2)

array([1., 1.])

In [7]:
np.empty(2)

array([1., 1.])

In [8]:
np.arange(4)

array([0, 1, 2, 3])

In [9]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [10]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
array = np.ones(2, dtype=int)
array

array([1, 1])

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
np.append(arr, [1, 2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [14]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [15]:
arr1 = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [16]:
np.sort(arr1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
array_example = np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],
                           [[0, 1, 2, 3],[4, 5, 6, 7]],
                            [[0 ,1 ,2, 3],[4, 5, 6, 7]]])
array_example.ndim

3

In [26]:
array_example.size

24

In [27]:
array_example.shape

(3, 2, 4)

In [28]:
a2 = np.arange(6)
print(a2)

[0 1 2 3 4 5]


In [29]:
b = a2.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [30]:
a3 = np.array([1, 2, 3, 4, 5, 6])
a3.shape

(6,)

In [31]:
a4 = a3[np.newaxis]
a4.shape

(1, 6)

In [32]:
row_vector = a3[np.newaxis, :]
row_vector.shape

(1, 6)

In [33]:
col_vector = a3[:, np.newaxis]
col_vector.shape

(6, 1)

In [34]:
a5 = np.array([1, 2, 3, 4, 5, 6])
a5.shape

(6,)

In [36]:
b1 = np.expand_dims(a5, axis=1)
b1.shape

(6, 1)

In [37]:
c = np.expand_dims(a5, axis=0)
c.shape

(1, 6)

In [38]:
data = np.array([1, 2, 3])
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

1
2
[1 2]
[2 3]
[2 3]


In [39]:
a6 = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a6[a6<5])

[1 2 3 4]


In [40]:
five_up = (a6 >= 5)
print(a6[five_up])

[ 5  6  7  8  9 10 11 12]


In [41]:
divisible_by_2 = a6[a6%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [42]:
c2 = a6[(a6 > 2) & (a6 < 11)]
print(c2)

[ 3  4  5  6  7  8  9 10]


In [44]:
five_up = (a6 > 5) | (a6 == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [45]:
a7 = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [47]:
b2 = np.where(a7<5)
print(b2)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [48]:
list_of_coordinates= list(zip(b2[0], b2[1]))
for cord in list_of_coordinates:
    print(cord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [49]:
print(a7[b2])

[1 2 3 4]


In [50]:
not_there = np.where(a7 == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [58]:
array = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr1 = array[3:8]
arr1

array([4, 5, 6, 7, 8])

In [61]:
array1 = np.array([[1, 1],[2, 2]])

In [62]:
array2 = np.array([[3, 3],[4, 4]])

In [63]:
np.vstack((array1, array2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [64]:
np.hstack((array1, array2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [65]:
array3 = np.array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [66]:
np.hsplit(array3,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [67]:
np.hsplit(array3,(3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [68]:
d = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [69]:
b = d.view()

In [70]:
c = d.copy()

In [71]:
a = np.array([1, 2, 3, 4])
# Add all of the elements in the array
a.sum()

10

In [72]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)

array([3, 3])

In [73]:
b.sum(axis=1)

array([2, 4])

In [78]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
[0.54627315, 0.05093587, 0.40067661, 0.55645993],
[0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [80]:
A.sum()


4.8595784

In [81]:
A.min()

0.05093587

In [82]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [83]:
np_arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [84]:
np_arr.shape

(3, 4)

In [85]:
num_of_rows = np_arr.shape[0]
print('Number of Rows : ', num_of_rows)

Number of Rows :  3


In [86]:
num_of_columns = np_arr.shape[1]
print('Number of Columns : ', num_of_columns)

Number of Columns :  4


In [87]:
print(np_arr.shape[0] * np_arr.shape[1])

12


In [88]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [89]:
print('Shape of 1D array: ', arr.shape)
print('Length of 1D array: ', arr.shape[0])

Shape of 1D array:  (8,)
Length of 1D array:  8


In [90]:
# get number of rows in array
num_of_rows2 = np.size(np_arr, 0)
# get number of columns in 2D numpy array
num_of_columns2 = np.size(np_arr, 1)
print('Number of Rows : ', num_of_rows2)
print('Number of Columns : ', num_of_columns2)

Number of Rows :  3
Number of Columns :  4


In [91]:
print('Total number of elements in  array : ', np.size(np_arr))

Total number of elements in  array :  12


In [92]:
arr3D = np.array([ [[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]],
               [[4, 4, 4, 4], [5, 5, 5, 5], [6, 6, 6, 6]] ])
print('Axis 0 size : ', np.size(arr3D, 0))
print('Axis 1 size : ', np.size(arr3D, 1))
print('Axis 2 size : ', np.size(arr3D, 2))

Axis 0 size :  2
Axis 1 size :  3
Axis 2 size :  4


In [93]:
print(np.size(arr3D))

24


In [101]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# Determine the length
print('Length of 1D numpy array : ', np.size(arr))

Length of 1D numpy array :  8


In [99]:
data = np.array([[1,2],[3,4],[5, 6]])
data[0,1]

2

In [100]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [102]:
data[0:2,0]

array([1, 3])

In [103]:
data.max()

6

In [104]:
data.min()

1

In [105]:
data.sum()

21

In [107]:
data.max(axis=0)
#data.max(axis=1)

array([5, 6])

In [108]:
#data.max(axis=0)
data.max(axis=1)

array([2, 4, 6])

In [110]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [111]:
np.ones(3)

array([1., 1., 1.])

In [113]:
np.zeros(3)

array([0., 0., 0.])

In [115]:
np.random.random((3))

array([0.52622261, 0.01975668, 0.86696841])

In [120]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [121]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [122]:
indices_list = np.unique(a, return_index=True)
print(indices_list)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]), array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))


In [123]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [124]:
a2D = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8] , [9, 10, 11, 12],  [1, 2, 3, 4]])

In [125]:
unique_values = np.unique(a2D)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [126]:
unique_rows = np.unique(a2D, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [127]:
unique_rows, occurence_count, indices = np.unique(a2D, axis=0, return_counts=True, return_index=True)
print('Unique Rows: ', '\n', unique_rows)
print('Occurrence Count:', '\n', occurence_count)
print('Indices: ', '\n', indices)

Unique Rows:  
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Occurrence Count: 
 [0 1 2]
Indices:  
 [2 1 1]


In [129]:
data.reshape(2,3)


array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [131]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [132]:
np.transpose(arr)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [133]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [134]:
reversed_arr = np.flip(arr)

In [135]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [136]:
arr2D = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [137]:
reversed_arr = np.flip(arr2D)
print('Reversed Array: ')
print(reversed_arr)

Reversed Array: 
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [138]:
reversed_arr_rows = np.flip(arr2D, axis=0)
print('Reversed Array: ')
print(reversed_arr_rows)

Reversed Array: 
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [139]:
reversed_arr_columns = np.flip(arr2D, axis=1)
print('Reversed Array columns: ')
print(reversed_arr_columns)

Reversed Array columns: 
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [140]:
arr2D[1] = np.flip(arr2D[1])
print('Reversed Array: ')
print(arr2D)

Reversed Array: 
[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [141]:
arr2D[:,1] = np.flip(arr2D[:,1])
print('Reversed Array: ')
print(arr2D)

Reversed Array: 
[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [142]:
array = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [143]:
array.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [144]:
a1 = array.flatten()
a1[0] = 100
print('Original array: ')
print(array)
print('New array: ')
print(a1)

Original array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
New array: 
[100   2   3   4   5   6   7   8   9  10  11  12]


In [145]:
a2 = array.ravel()
a2[0] = 101
print('Original array: ')
print(array)
print('New array: ')
print(a2)

Original array: 
[[101   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
New array: 
[101   2   3   4   5   6   7   8   9  10  11  12]


In [146]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [147]:
a = np.array([1, 2, 3, 4, 5, 6])

In [148]:
a?

In [149]:
def double(a):
  '''Return a * 2'''
  return a * 2

In [150]:
double?

In [151]:
a = np.array([1, 2, 3, 4, 5, 6])
np.save('filename',a)
b = np.load('filename.npy')
print(b)

[1 2 3 4 5 6]


In [152]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.savetxt('new_file.csv', csv_arr)
np.loadtxt('new_file.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])